app/__init__.py
import os
from flask import Flask
from flask_moment import Moment
from flask_debugtoolbar import DebugToolbarExtension
from flask_flatpages import FlatPages
from flask_frozen import Freezer

from werkzeug.contrib.fixers import ProxyFix

from config import config, basedir

from htmlabbrev import HTMLAbbrev

moment = Moment()
toolbar = DebugToolbarExtension()
pages = FlatPages()
freezer = Freezer()

def htmltruncate(value, maxlen=150):
    parser = HTMLAbbrev(maxlen)
    parser.feed(value)
    return parser.close()

def create_app(config_name):

    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    moment.init_app(app)
    toolbar.init_app(app)
    pages.init_app(app)
    freezer.init_app(app)

    from main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from blog import blog as blog_blueprint
    app.register_blueprint(blog_blueprint, url_prefix='/blog')

    app.wsgi_app = ProxyFix(app.wsgi_app)

    app.jinja_env.filters['htmltruncate'] = htmltruncate

    if not os.path.exists(os.path.join(basedir, 'tmp')):
        os.makedirs(os.path.join(basedir, 'tmp'))

    if not app.debug:
        import logging
        from logging.handlers import RotatingFileHandler, SMTPHandler

        file_handler = RotatingFileHandler('tmp/healy.log', 'a', 1 * 1024 * 1024, 10)
        file_handler.setFormatter(logging.Formatter('%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'))
        app.logger.setLevel(logging.INFO)
        file_handler.setLevel(logging.INFO)
        app.logger.addHandler(file_handler)
        app.logger.info('healy startup')

    return app

app/blog/__init__.py
from flask import Blueprint

blog = Blueprint('blog', __name__)

from . import views

app/blog/views.py
from flask import render_template, current_app, abort
from . import blog
from .. import pages
from .. import htmltruncate
from werkzeug.contrib.atom import AtomFeed

@blog.context_processor
def inject_debug():
    return dict(debug = current_app.config['DEBUG'])

@blog.route('/', methods=['GET'])
def index():

    latest = sorted(pages, reverse=True, key=lambda p: p.meta['timestamp'])

    return render_template("blog/index.html",title='Blog',posts=latest[:5])

@blog.route('/post/list/', methods=['GET'])
def archives():

    posts = (p for p in pages)
    posts = sorted(posts, reverse=True, key=lambda p: p.meta['timestamp'])

    return render_template("blog/archives.html",title='Posts',posts=posts)

@blog.route('/post/tagged/<tag>/', methods=['GET'])
def view_tagged_posts(tag):

    tagged = [p for p in pages if tag in p.meta.get('tags', [])]

    posts = sorted(tagged, reverse=True, key=lambda p: p.meta['timestamp'])

    if not posts:
        abort(404)

    return render_template("blog/post.html",posts=posts,title=tag)

@blog.route('/post/<slug>/', methods=['GET'])
def view_post(slug):

    post = pages.get(slug)

    if not post:
        abort(404)

    return render_template("blog/post.html",posts=[post],title=post.meta['title'])

@blog.route('/recent.atom')
def recent_feed():

    feed = AtomFeed('Matt Healy Web Solutions - Recent Articles',
                    feed_url='https://www.matthealy.com.au/blog/recent.atom', url='https://www.matthealy.com.au')

    latest = sorted(pages, reverse=True, key=lambda p: p.meta['timestamp'])

    for post in latest[:15]:

        html = htmltruncate(post.html,900) + \
               '<a href="' + \
               'https://www.matthealy.com.au/blog/post/' + post.meta['slug'] + '/' + \
               '">Read More</a>'

        feed.add(post.meta['title'], unicode(html),
                 content_type='html',
                 author=post.meta['author'],
                 url='https://www.matthealy.com.au/blog/post/'+post.meta['slug']+'/',
                 updated=post.meta['timestamp'])

    return feed.get_response()

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views, errors

app/main/views.py
from flask import render_template, current_app, Response
from . import main
from .. import pages

@main.context_processor
def inject_debug():
    return dict(debug = current_app.config['DEBUG'])

@main.route('/', methods=['GET','POST'])
def index():

    languages = ['Python','Perl','PHP','SQL','HTML','CSS','Javascript']

    frameworks = ['Flask','jQuery','Wordpress','Twitter Bootstrap']

    software = ['MySQL','Linux','Apache','Nginx','Git','Sendmail','Swagger','Xero']

    other = ['Amazon Web Services','Google Apps','Github','JSON','REST','SOAP','XML','DNS','SMTP','Domain Names']

    return render_template("index.html", languages=languages, \
                            frameworks=frameworks, softwares=software, \
                            others=other)

@main.route('/about/', methods=['GET'])
def about():
    return render_template("about.html")

@main.route('/portfolio/', methods=['GET'])
def portfolio():
    return render_template("portfolio.html")

@main.route('/contact/', methods=['GET'])
def contact():
    return render_template("contact.html")

@main.route('/services/', methods=['GET'])
def services():
    return render_template("services.html")

@main.route('/terms/', methods=['GET'])
def terms():
    return render_template("terms.html")

@main.route('/sitemap.xml', methods=['GET'])
def sitemapxml():

    sitemap = """<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://www.matthealy.com.au/</loc>
  </url>
  <url>
    <loc>https://www.matthealy.com.au/about/</loc>
  </url>
  <url>
    <loc>https://www.matthealy.com.au/contact/</loc>
  </url>
  <url>
    <loc>https://www.matthealy.com.au/portfolio/</loc>
  </url>
  <url>
    <loc>https://www.matthealy.com.au/services/</loc>
  </url>
  <url>
    <loc>https://www.matthealy.com.au/terms/</loc>
  </url>
  <url>
    <loc>https://www.matthealy.com.au/blog/</loc>
  </url>
  <url>
    <loc>https://www.matthealy.com.au/blog/post/list/</loc>
  </url>"""

    tags = []
    posts = (p for p in pages)
    posts = sorted(posts, key=lambda p: p.meta['timestamp'])

    for post in posts:
        for tag in post.meta['tags']:
            tags.append(tag)
        sitemap = sitemap + "\n  <url>\n    <loc>https://www.matthealy.com.au/blog/post/" + post.meta['slug'] + "/</loc>\n  </url>"

    for tag in tags:
        sitemap = sitemap + "\n  <url>\n    <loc>https://www.matthealy.com.au/blog/post/tagged/" + tag + "/</loc>\n  </url>"
  
    sitemap = sitemap + "\n</urlset>"

    return Response(sitemap, mimetype='text/xml')

@main.route('/robots.txt', methods=['GET'])
def robots():

    robots = """User-agent: *
Allow: /"""

    return Response(robots, mimetype='text/plain')

# This route is only used for Flask-Frozen to generate a static error.html page
@main.route('/error.html', methods=['GET'])
def error_static_page():
    return render_template("404.html")

app/templates/about.html
{% extends "base.html" %}
{% block content %}

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">About
                        <strong>Matt Healy Web Solutions</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-md-6">
                    <img class="img-responsive img-border-left" src="{{ url_for('static', filename='img/slide-3.jpg') }}" alt="">
                </div>
                <div class="col-md-6">
                    <p>I graduated from Murdoch University in Perth, Western Australia, June 2007. Since then I have been working in the web industry and gaining experience as a web developer, database administrator, server guy, team leader, client liaison, consultant and business analyst.</p>
                    <p>I am a proud father of two beautiful children and enjoy movies, sports and technology in my spare time.</p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-md-6">
                    <a class="twitter-timeline" data-dnt="true" href="https://twitter.com/matt_healy" data-widget-id="692723812836646912">Tweets by @matt_healy</a>
                    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
                </div>
                <div class="col-md-6">
                    <img class="img-responsive img-border-left" src="{{ url_for('static', filename='img/about-pic.jpg') }}" alt="">
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="Matt Healy Web Solutions - Web Developer - Perth, Western Australia">
    <meta name="author" content="Matt Healy">

    {% if title %}
    <title>{{ title }} - Matt Healy Web Solutions - Web Developer - Perth, Western Australia</title>
    {% else %}
    <title>Matt Healy Web Solutions - Web Developer - Perth, Western Australia</title>
    {% endif %}

    <link href="https://www.matthealy.com.au/blog/recent.atom" rel="alternate" title="Matt Healy Web Solutions - Recent Changes" type="application/atom+xml">

    <link rel="canonical" href="https://www.matthealy.com.au{{ request.path }}">

    <!-- Bootstrap Core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{ url_for('static', filename='css/business-casual.css') }}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="brand">Matt Healy Web Solutions</div>
    <div class="address-bar">Perth, Western Australia | 0403 429 865</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Home</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{{ url_for('main.index') }}">Home</a>
                    </li>
                    <li>
                        <a href="{{ url_for('main.services') }}">Services</a>
                    </li>
                    <li>
                        <a href="{{ url_for('main.portfolio') }}">Portfolio</a>
                    </li>
                    <li>
                        <a href="{{ url_for('main.about') }}">About</a>
                    </li>
                    <li>
                        <a href="{{ url_for('main.contact') }}">Contact</a>
                    </li>
                    <li>
                        <a href="{{ url_for('blog.index') }}">Blog</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">

                {% block content %}
                {% endblock %}

    </div>
    <!-- /.container -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Matt Healy {{ moment().format('YYYY') }}<br /><a href="{{ url_for('main.terms') }}">Terms &amp; Conditions / Privacy</a></p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

    {{ moment.include_moment() }}

{% if not debug %}

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43045289-1', 'auto');
  ga('send', 'pageview');

</script>

{% endif %}

</body>

</html>

app/templates/blog/_post_tags.html
                    {% if post.tags %}
                        <p class="post-meta">Tagged under:
                        {% for tag in post.tags %}
                            <a href="{{ url_for('blog.view_tagged_posts', tag=tag)}}">{{ tag }}</a>{% if not loop.last %},{% endif %}
                        {% endfor %}
                        </p>
                    {% endif %}

app/templates/blog/_posts.html
    {% for post in posts %}

                <a name="top">&nbsp;</a>

                <div class="col-lg-12 text-justify">
                    <div class="text-center">
                    <h2>
                        <a href="{{ url_for("blog.view_post", slug=post.slug) }}">{{ post.title }}</a>
                        <br>
                        <small>{{ moment(post.timestamp).format("Do MMM YYYY") }}</small>
                    </h2>
                    </div>
                    {{ post.html | safe }}
                    {% include "blog/_post_tags.html" %}
                    <hr>
                </div>

    {% endfor %}

app/templates/blog/_posts_short.html
    {% for post in posts %}

                <div class="col-lg-12 text-center">
                    <h2>
                        <a href="{{ url_for("blog.view_post", slug=post.slug) }}">{{ post.title }}</a>
                        <br>
                        <small>{{ moment(post.timestamp).format("Do MMM YYYY") }}</small>
                    </h2>
                    {% include "blog/_post_tags.html" %}
                    <hr>
                </div>

    {% endfor %}

app/templates/blog/_posts_truncate.html
    {% for post in posts %}

                <div class="col-lg-12 text-justify">
                    <div class="text-center">
                    <h2>
                        <a href="{{ url_for("blog.view_post", slug=post.slug) }}">{{ post.title }}</a>
                        <br>
                        <small>{{ moment(post.timestamp).format("Do MMM YYYY") }}</small>
                    </h2>
                    </div>
                    <p>{{ post.html | htmltruncate(900) | safe }}</p>
                    <a href="{{ url_for("blog.view_post", slug=post.slug) }}" class="btn btn-default btn-lg">Read More</a>
                    {% include "blog/_post_tags.html" %}
                    <hr>
                </div>

    {% endfor %}

app/templates/blog/archives.html
{% extends "base.html" %}
{% block content %}

        <div class="row">
            <div class="box">

    {% include 'blog/_posts_short.html' %}

            </div>
        </div>

{% endblock %}

app/templates/blog/edit.html
{% extends "base.html" %}

{% block content %}

    <h2>{% if form.id.data > 0 %}Edit Post{% else %}Add Post{% endif %}</h2>

    <form class="form" method="post">
        {{ form.hidden_tag() }}
        <label for="title">Title</label>
        {{ form.title(placeholder="Title", class="form-control") }}
        {% for error in form.errors.title %}<div style="color: red;">[{{error}}]</div>{% endfor %}
        <label for="title">Tags</label>
        {{ form.tags(placeholder="Tags, separated by comma", class="form-control") }}
        {% for error in form.errors.tags %}<div style="color: red;">[{{error}}]</div>{% endfor %}
        <label for="content">Post</label>
        {{ form.content(placeholder="Post Content", class="form-control", rows=10) }}
        {% for error in form.errors.content %}<div style="color: red;">[{{error}}]</div>{% endfor %}
        {{ form.submit(class="btn btn-lg btn-primary btn-block") }}
    </form>

{% endblock %}

app/templates/blog/index.html
{% extends "base.html" %}
{% block content %}

        <div class="row">
            <div class="box">

    {% include 'blog/_posts_truncate.html' %}

                <div class="col-lg-12 text-center">
                    <ul class="pager">
                        <li class="previous"><a href="{{ url_for('blog.archives') }}">&larr; Older Posts</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>


{% endblock %}

app/templates/blog/login.html
{% extends "base.html" %}

{% block styles %}

    {{ super() }}

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename="css/signin.css") }}" />

{% endblock %}

{% block content %}

      <form class="form-signin" method="post">
        {{ form.hidden_tag() }}
        <h2 class="form-signin-heading">Admin Sign In</h2>
        <label for="inputEmail" class="sr-only">Email address</label>
        {{ form.email(placeholder="Email address", class="form-control") }}
        {% for error in form.errors.email %}
           <span style="color: red;">[{{error}}]</span>
        {% endfor %}

        <label for="inputPassword" class="sr-only">Password</label>
        {{ form.password(placeholder="Password", class="form-control") }}
        {% for error in form.errors.password %}
           <span style="color: red;">[{{error}}]</span>
        {% endfor %}
        <div class="checkbox">
          <label>
            {{ form.remember_me }} Remember me
          </label>
        </div>
        {{ form.submit(class="btn btn-lg btn-primary btn-block") }}
      </form>

{% endblock %}

app/templates/blog/post.html
{% extends "base.html" %}
{% block content %}

        <div class="row">
            <div class="box">

    {% include 'blog/_posts.html' %}

            </div>
        </div>

{% endblock %}

app/templates/contact.html
{% extends "base.html" %}
{% block content %}

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Contact
                        <strong>Matt Healy Web Solutions</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-md-8">
                    <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
                    <iframe width="100%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1692.659159057527!2d115.85773065801538!3d-31.952259995307212!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMzHCsDU3JzA4LjEiUyAxMTXCsDUxJzMxLjgiRQ!5e0!3m2!1sen!2sau!4v1451736222497"></iframe>
                </div>
                <div class="col-md-4">
                    <p>Phone:
                        <strong>0403 429 865</strong>
                    </p>
                    <p>Email:
                        <strong><a href="mailto:matt@matthealy.com.au">matt@matthealy.com.au</a></strong>
                    </p>
                    <br />
                    <p>Around the web:</p>
                    <p><a href="https://www.facebook.com/healyconsulting/"><i class="fa fa-facebook-official"></i> Facebook</a></p>
                    <p><a href="https://twitter.com/matt_healy"><i class="fa fa-twitter"></i> Twitter</a></p>
                    <p><a href="https://github.com/MattHealy/"><i class="fa fa-github"></i> GitHub</a></p>
                    <p><a href="http://stackoverflow.com/users/272193/matthewh"><i class="fa fa-stack-overflow"></i> Stack Overflow</a></p>
                    <p><a href="https://www.linkedin.com/in/mjhealy"><i class="fa fa-linkedin"></i> LinkedIn</a></p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block content %}

        <div class="row">
            <div class="box">
                <div class="col-lg-12 text-center">
                    <div id="carousel-example-generic" class="carousel slide">
                        <!-- Indicators -->
                        <ol class="carousel-indicators hidden-xs">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                            <div class="item active">
                                <img class="img-responsive img-full" src="{{ url_for('static', filename='img/slide-4.jpg') }}" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="{{ url_for('static', filename='img/slide-5.jpg') }}" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="{{ url_for('static', filename='img/slide-6.jpg') }}" alt="">
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="icon-next"></span>
                        </a>
                    </div>
                    <!--
                    <h2 class="brand-before">
                        <small>Welcome to</small>
                    </h2>
                    <h1 class="brand-name">Matt Healy Web Solutions</h1>
                    <hr class="tagline-divider">
                    <h2>
                        <small>By
                            <strong>Matt Healy</strong>
                        </small>
                    </h2>
                    -->
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Matt Healy
                        <strong>Web Solutions</strong>
                    </h2>
                    <hr>
                    <img class="img-responsive img-border img-left" src="{{ url_for('static', filename='img/intro-pic.jpg') }}" alt="">
                    <hr class="visible-xs">
                    <p>Matt Healy Web Solutions is a small web consultancy based in Perth, Western Australia. I primarily specialise in creating custom web based applications. I also have expertise in Linux server management, Amazon Web Services, domain names, and much more.</p>
                    <p><a href="{{ url_for('main.contact') }}">Contact me</a> today to see how I can assist your business to take advantage of the web.</p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <p><strong>Programming/Markup Languages:</strong>
                    <ul class="list-inline" style="font-size: 18px; line-height: 36px">
                        {% for language in languages %}
                        <li><span class="label label-primary">{{ language }}</span></li>
                        {% endfor %}
                    </ul>
                    </p>
                    <p><strong>Frameworks:</strong>
                    <ul class="list-inline" style="font-size: 18px; line-height: 36px">
                        {% for framework in frameworks %}
                        <li><span class="label label-info">{{ framework }}</span></li>
                        {% endfor %}
                    </ul>
                    </p>
                    <p><strong>Software:</strong>
                    <ul class="list-inline" style="font-size: 18px; line-height: 36px">
                        {% for software in softwares %}
                        <li><span class="label label-success">{{ software }}</span></li>
                        {% endfor %}
                    </ul>
                    </p>
                    <p><strong>Other:</strong>
                    <ul class="list-inline" style="font-size: 18px; line-height: 36px">
                        {% for other in others %}
                        <li><span class="label label-default">{{ other }}</span></li>
                        {% endfor %}
                    </ul>
                    </p>
                </div>
            </div>
        </div>

{% endblock %}

app/templates/portfolio.html
{% extends "base.html" %}
{% block content %}

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Portfolio
                    </h2>
                    <hr>
                </div>
                <div class="col-md-6">
                    <a href="{{ url_for('static', filename='img/portfolio/foodloggr.png') }}"><img class="img-responsive img-border-left" src="{{ url_for('static', filename='img/portfolio/foodloggr.png') }}" alt=""></a>
                </div>
                <div class="col-md-6">
                    <h3>foodloggr</h3>
                    <p>Traditional food logging apps require more effort than they really should. You have to search for food items in an enormous database, where official entries are mixed in with user-submitted entries, and a lot of the time those databases are very US-centric. This makes it difficult to track what you are eating, often leading to just giving up on using the service. foodloggr aims to simplify that process – you just enter what you eat, that’s it.</p>
                    <p>foodloggr is built using the Flask framework for Python, and is hosted on Amazon EC2 with user content stored on S3.</p>
                    <p>foodloggr was covered by <a href="http://www.startupnews.com.au">//Startup News</a> in October 2015. You can read the article <a href="http://www.startupnews.com.au/2015/10/06/foodloggr/">here</a>.</p>
                    <!--<p><a href="https://www.foodloggr.com">Try foodloggr today!</a></p>-->
                </div>
                <div class="clearfix"></div>
                <div class="col-md-12">
                    <hr>
                </div>
                <div class="col-md-6">
                    <a href="{{ url_for('static', filename='img/portfolio/qrbyte.png') }}"><img class="img-responsive img-border-left" src="{{ url_for('static', filename='img/portfolio/qrbyte.png') }}" alt=""></a>
                </div>
                <div class="col-md-6">
                    <h3>qrByte</h3>
                    <p>qrByte is a simple web application that allows users to create intelligent QR codes. The QR codes are capable of detecting the type of mobile device being used for scanning, and redirecting the user to the appropriate URL based on their device type. Perfect for QR codes linking to apps on the iTunes and Google Play stores!</p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

{% endblock %}